/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.internship.frejaeidjmeterplugin.gui;

import org.apache.jmeter.samplers.gui.AbstractSamplerGui;
import org.apache.jmeter.testelement.TestElement;

/**
 *
 * @author Ivan
 */
public class AuthSamplerGui extends AbstractSamplerGui {

    /**
     * Creates new form AuthSampler
     */
    public AuthSamplerGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblInitAuth = new javax.swing.JLabel();
        btnSendInitAuth = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInitAuth.setText("InitAuth");

        btnSendInitAuth.setText("SEND");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblInitAuth)
                .addGap(118, 118, 118)
                .addComponent(btnSendInitAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInitAuth)
                    .addComponent(btnSendInitAuth))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getLabelResource() {
        return "AuthSamplerGui";
    }

    @Override
    public TestElement createTestElement() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void modifyTestElement(TestElement te) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void configure(TestElement element) {
         super.configure(element);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendInitAuth;
    private javax.swing.JLabel lblInitAuth;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
