/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.internship.frejaeidjmeterplugin.jmeter.gui;

import com.internship.frejaeidjmeterplugin.jmeter.sample.AuthSample;
import com.verisec.frejaeid.client.beans.authentication.get.AuthenticationResult;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import org.apache.jmeter.samplers.gui.AbstractSamplerGui;
import org.apache.jmeter.testelement.TestElement;

/**
 *
 * @author Ivan
 */
public class AuthSamplerGui extends AbstractSamplerGui {

    /**
     * Creates new form AuthSamplerGui
     */
    public AuthSamplerGui() {
        initComponents();
        init();
    }

    private void init() {
        setBorder(makeBorder());
        Box box = Box.createVerticalBox();
        box.add(makeTitlePanel());
        add(box, BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInitAuthenticate = new javax.swing.JLabel();
        btnSendInitAuthenticate = new javax.swing.JButton();
        lblStatusTitle = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        lblInitAuthenticate.setText("InitAuthenticate");

        btnSendInitAuthenticate.setText("Send");
        btnSendInitAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendInitAuthenticateActionPerformed(evt);
            }
        });

        lblStatusTitle.setText("Status:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInitAuthenticate)
                    .addComponent(lblStatusTitle))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(btnSendInitAuthenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInitAuthenticate)
                    .addComponent(btnSendInitAuthenticate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusTitle)
                    .addComponent(lblStatus))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendInitAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendInitAuthenticateActionPerformed
        // TODO add your handling code here:
        AuthSample auth = AuthSample.getInstance();
        AuthenticationResult result = auth.sendInitAuthenticate();
        String status = result.getStatus() + "";
        lblStatus.setText(status);
        if (status.equals("CANCELED")) {
            lblStatus.setForeground(Color.red);
        } else if (status.equals("APPROVED")){
            lblStatus.setForeground(Color.green);
        }
    }//GEN-LAST:event_btnSendInitAuthenticateActionPerformed

    @Override
    public String getLabelResource() {
        return this.getClass().getSimpleName();
    }

    @Override
    public void configure(TestElement element) {
        super.configure(element);
    }

    @Override
    public String getStaticLabel() {
        return "InitAuthRequest";
    }

    @Override
    public TestElement createTestElement() {
        AuthSample auth = AuthSample.getInstance();
        modifyTestElement(auth);
        return auth;
    }

    @Override
    public void modifyTestElement(TestElement te) {
        AuthSample auth = (AuthSample) te;
    }

    public JButton getBtnSendInitAuthenticate() {
        return btnSendInitAuthenticate;
    }

    public JLabel getLblInitAuthenticate() {
        return lblInitAuthenticate;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendInitAuthenticate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInitAuthenticate;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusTitle;
    // End of variables declaration//GEN-END:variables
}
